# Generated by Django 3.2.4 on 2021-06-30 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user1_id', models.CharField(max_length=50)),
                ('user2_id', models.CharField(max_length=50)),
                ('user1_state', models.CharField(choices=[('ACC', 'Accepted'), ('CAN', 'Cancelled'), ('ATA', 'AwaitingTheirAcceptance'), ('AYA', 'AwaitingYourAcceptance'), ('WBM', 'WithdrawnByMe'), ('WBT', 'WithdrawnByThem')], default='ATA', max_length=3)),
                ('user2_state', models.CharField(choices=[('ACC', 'Accepted'), ('CAN', 'Cancelled'), ('ATA', 'AwaitingTheirAcceptance'), ('AYA', 'AwaitingYourAcceptance'), ('WBM', 'WithdrawnByMe'), ('WBT', 'WithdrawnByThem')], default='ATA', max_length=3)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('version', models.IntegerField()),
            ],
        ),
    ]
