# Generated by Django 3.2.4 on 2021-06-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('user1_state', models.CharField(choices=[('ACC', 'Accepted'), ('CAN', 'Cancelled'), ('ATA', 'AwaitingTheirAcceptance'), ('AYA', 'AwaitingYourAcceptance'), ('WBM', 'WithdrawnByMe'), ('WBT', 'WithdrawnByThem')], default='ATA', max_length=3)),
                ('user2_state', models.CharField(choices=[('ACC', 'Accepted'), ('CAN', 'Cancelled'), ('ATA', 'AwaitingTheirAcceptance'), ('AYA', 'AwaitingYourAcceptance'), ('WBM', 'WithdrawnByMe'), ('WBT', 'WithdrawnByThem')], default='ATA', max_length=3)),
                ('product_name', models.CharField(max_length=50)),
                ('buyer', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
